[titles]
masteradmin = "MasterAdmin"
admin = "Admin"
operator = "Operator"

[masteradmins]
tmlogin = []
ipaddress = []

[admins]
tmlogin = []
ipaddress = []

[operators]
tmlogin = []
ipaddress = []

[abilities]

[abilities.admin]
access = false
acdl = false
add = true
addadmin = false
addguest = true
addlocal = true
addop = true
addthis = true
adminability = false
admpanel = false
autotime = true
ban = true
banip = true
black = true
call = true
can = true
cancel = true
chat_add_tref = false
chat_bestworst = true
chat_jb_multi = true
chat_jb_recent = true
chat_jfreu = true
chat_jukebox = true
chat_match = false
chat_musicadmin = true
chat_pma = true
chat_settings = true
chat_statsip = true
chat_summary = true
chat_tc_listen = false
cjb = true
cleanbanlist = false
cleanblacklist = false
cleanguestlist = false
cleanignores = false
cleaniplist = false
cleanmutes = false
clearhist = true
clearjukebox = true
coppers = true
debug = false
delrec = false
disablerespawn = true
djb = true
donpanel = false
dropjukebox = true
endround = true
er = true
erase = true
erasethis = true
eyeset = false
forceshowopp = true
forcespec = true
forceteam = true
help = true
helpall = true
ignore = true
ignorelist = true
kick = true
kickghost = true
listabilities = true
listadmins = true
listbans = true
listblacks = true
listdupes = true
listguests = true
listignores = true
listips = true
listmasters = true
listmutes = true
listops = true
match = true
mergegbl = false
mta = true
mute = true
mutelist = true
next = true
nextenv = true
nextmap = true
noidlekick_play = false
noidlekick_spec = true
opability = false
panel = true
pass = true
pay = false
players = true
pm = true
pmlog = true
prev = true
previous = true
prunerecs = false
readabilities = true
readblacklist = true
readguestlist = true
readiplist = true
readtracklist = true
recpanel = false
relays = true
remove = true
removeadmin = false
removeguest = true
removeop = true
removethis = true
replay = true
replaymap = true
res = true
restart = true
restartmap = true
roundsfinish = true
rpoints = true
rt = false
scorepanel = true
server = true
server_coppers = true
setcomment = false
setgamemode = true
setmaxplayers = false
setmaxspecs = false
setpwd = true
setrefmode = true
setrefpwd = true
setservername = false
setspecpwd = true
showbanlist = true
showblacklist = true
showguestlist = true
showiplist = true
shuffle = true
shufflemaps = true
shutdown = false
shutdownall = false
skip = true
skipmap = true
specfree = true
style = false
unban = true
unbanip = true
unblack = true
unignore = true
unlock = true
unmute = true
uptodate = true
votepanel = false
wall = true
warn = true
writeabilities = true
writeblacklist = true
writeguestlist = true
writeiplist = true
writetracklist = true

[abilities.operator]
access = false
acdl = false
add = false
addadmin = false
addguest = true
addlocal = false
addop = false
addthis = false
adminability = false
admpanel = false
autotime = false
ban = false
banip = false
black = false
call = false
can = true
cancel = true
chat_add_tref = false
chat_bestworst = false
chat_jb_multi = false
chat_jb_recent = false
chat_jfreu = false
chat_jukebox = false
chat_match = false
chat_musicadmin = false
chat_pma = false
chat_settings = true
chat_statsip = false
chat_summary = false
chat_tc_listen = false
cjb = true
cleanbanlist = false
cleanblacklist = false
cleanguestlist = false
cleanignores = false
cleaniplist = false
cleanmutes = false
clearhist = false
clearjukebox = true
coppers = false
debug = false
delrec = false
disablerespawn = false
djb = true
donpanel = false
dropjukebox = true
endround = true
er = true
erase = false
erasethis = false
eyeset = false
forceshowopp = false
forcespec = true
forceteam = true
help = true
helpall = true
ignore = true
ignorelist = true
kick = true
kickghost = true
listabilities = true
listadmins = true
listbans = true
listblacks = true
listdupes = false
listguests = true
listignores = true
listips = true
listmasters = true
listmutes = true
listops = true
match = false
mergegbl = false
mta = false
mute = true
mutelist = true
next = true
nextenv = true
nextmap = true
noidlekick_play = false
noidlekick_spec = true
opability = false
panel = true
pass = true
pay = false
players = true
pm = false
pmlog = false
prev = true
previous = true
prunerecs = false
readabilities = false
readblacklist = false
readguestlist = false
readiplist = false
readtracklist = false
recpanel = false
relays = true
remove = false
removeadmin = false
removeguest = true
removeop = false
removethis = false
replay = true
replaymap = true
res = true
restart = true
restartmap = true
roundsfinish = true
rpoints = false
rt = false
scorepanel = true
server = false
server_coppers = false
setcomment = false
setgamemode = false
setmaxplayers = false
setmaxspecs = false
setpwd = false
setrefmode = false
setrefpwd = false
setservername = false
setspecpwd = false
showbanlist = true
showblacklist = true
showguestlist = true
showiplist = true
shuffle = false
shufflemaps = false
shutdown = false
shutdownall = false
skip = true
skipmap = true
specfree = true
style = false
unban = false
unbanip = false
unblack = false
unignore = true
unlock = true
unmute = true
uptodate = false
votepanel = false
wall = false
warn = true
writeabilities = false
writeblacklist = false
writeguestlist = false
writeiplist = false
writetracklist = false
