[colors]
error = "$f00$i"
welcome = "$f00"
server = "$ff0"
highlite = "$fff"
timelite = "$bbb"
record = "$0f3"
emotic = "$fa0"
music = "$d80"
message = "$39f"
rank = "$ff3"
vote = "$f8f"
karma = "$ff0"
donate = "$f0f"
admin = "$ff0"
black = "$000"
grey = "$888"
login = "$00f"
logina = "$0c0"
nick = "$f00"
interact = "$ff0$i"
dedimsg = "$28b"
dedirec = "$0b3"

[sys_messages]
sys_startup = "{#server}*** PyXaseco {#highlite}v{1}{#server} running on {#highlite}{2}{#server}:{#highlite}{3}{#server} ***"
sys_welcome = "{#welcome}Welcome {#highlite}{1}{#welcome} to {#highlite}{2}$z$s{br}{#welcome}This server uses {#highlite}{3}{#welcome} to manage your records."
sys_warning = "$s{#welcome}This is an administrative warning.{br}{br}$gWhatever you wrote is against our server's{br}policy. Not respecting other players, or{br}using offensive language might result in a{br}{#welcome}kick, or ban {#message}the next time.{br}{br}$gThe server administrators."
sys_record_current = "{#server}>> {#message}Current record on {#highlite}{1}{#message} is {#highlite}{2}{#message} by {#highlite}{3}"
sys_record_none = "{#server}>> {#message}Currently no record on {#highlite}{1}{#message} ..."
sys_record_error = "{#server}>> {#error}Could not get records from database... No records this round!"
sys_ranking = "{#server}>> {#message}Local Record rankings on {#highlite}{1}{#message} {2} this round:"
sys_ranking_range = "{#server}>> {#message}Local Record rankings on {#highlite}{1}{#message} {2} this round (range {#highlite}{3}{#message}):"
sys_ranking_new = "{#server}>> {#message}Local Record rankings on {#highlite}{1}{#message} {2} this round ({#highlite}{3}{#message} new):"
sys_ranking_nonew = "{#server}>> {#message}Local Record rankings on {#highlite}{1}{#message} {2} this round: none new so far"
sys_ranking_none = "{#server}>> {#message}Local Record rankings on {#highlite}{1}{#message} {2} this round: no records!"
sys_ranking_record_new_on = "{#rank}{1}{#message}.$i{#highlite}{2}{#message}[{#highlite}{3}{#message}]$i, "
sys_ranking_record_new = "{#rank}{1}{#message}.{#highlite}{2}{#message}[{#highlite}{3}{#message}], "
sys_ranking_record_on = "{#rank}{1}{#message}.$i{#timelite}{2}{#message}[{#timelite}{3}{#message}]$i, "
sys_ranking_record = "{#rank}{1}{#message}.{#timelite}{2}{#message}[{#timelite}{3}{#message}], "
sys_ranking_record2 = "{#rank}{1}{#message}.{#timelite}{2}{#message}, "
sys_first_record = "{#server}> {#record}The first Local record is: "
sys_last_record = "{#server}> {#record}The last Local record is: "
sys_diff_record = "{#server}> {#record}Difference between {1}{#record} and {2}{#record} is: {#highlite}{3}"
sys_summary = "{#server}> {#highlite}{1} $z$s{#record}has {#highlite}{2}{#record} Local record{3}, the top {4} being: "
sys_sum_entry = "{#highlite}{1} {#record}rec{2} #{#rank}{3}{#record}, "
sys_wins = "{#server}> {#record}You have already won {#highlite}{1}{#record} race{2}"
sys_win_new = "{#server}> {#record}Congratulations, you won your {#highlite}{1}{#record}. race!"
sys_win_multi = "{#server}>> {#record}Congratulations, {#highlite}{1}{#record} won his/her {#highlite}{2}{#record}. race!"
sys_mute = "{#server}> Player {#highlite}{1}$z$s{#server} is muted!"
sys_unmute = "{#server}> Player {#highlite}{1}$z$s{#server} is unmuted!"
sys_muted = "{#server}> {#highlite}{1}{#error} disabled because you are on the global mute list!"
sys_donation = "{#donate} Donate {#highlite}{1}{#donate} coppers to {#highlite}{2}$z"
sys_thanks_all = "{#server}>> {#highlite}{1}$z$s{#donate} received a donation of {#highlite}{2}{#donate} coppers from {#highlite}{3}$z$s{#donate}.  Thank You!"
sys_thanks_you = "{#server}> {#donate}You made a donation of {#highlite}{1}{#donate} coppers.  Thank You!"
sys_donate_minimum = "{#server}> {#error}Minimum donation amount is {#highlite}$i {1}{#error} coppers!"
sys_donate_help = "{#server}> {#error}Use {#highlite}$i /donate <number>{#error} to donate coppers to the server"
sys_payment = "{#donate} Send {#highlite}{1}{#donate} coppers to {#highlite}{2}$z"
sys_pay_insuff = "{#server}> {#error}Insufficient server coppers: {#highlite}$i {1}{#error}!"
sys_pay_server = "{#server}> {#error}Cannot pay this server itself!"
sys_pay_confirm = "{#server}> {#donate}Payment of {#highlite}{1}{#donate} coppers to {#highlite}{2}{#donate} confirmed!  Remaining coppers: {#highlite}{3}"
sys_pay_cancel = "{#server}> {#donate}Payment to {#highlite}{1}{#donate} cancelled!"
sys_pay_help = "{#server}> {#error}Use {#highlite}$i /admin pay <login> $m<number>{#error} to send server coppers to a login"
sys_playtime = "{#server}> Current track {#highlite}{1}{#server} has been played for {#highlite}{2}"
sys_playtime_finish = "{#server}>> Current track {#highlite}{1}{#server} finished after {#highlite}{2}"
sys_playtime_replay = " {#server}({#highlite}{1}{#server} replay{2}, total {#highlite}{3}{#server})"
sys_track = "{#server}> Current track {#highlite}{1} {#server}by {#highlite}{2}  {#server}Author: {#highlite}{3} {#server}Gold: {#highlite}{4} {#server}Silver: {#highlite}{5} {#server}Bronze: {#highlite}{6} {#server}Cost: {#highlite}{7}"
sys_current_track = "{#server}>> Current track {#highlite}{1} {#server}by {#highlite}{2}  {#server}Author: {#highlite}{3}"
sys_rpoints_named = "{#server}> {1}Custom points system set to {#highlite}{2}{3}: {#highlite}{4},..."
sys_rpoints_nameless = "{#server}> {1}Custom points system set to: {#highlite}{2},..."
sys_no_rpoints = "{#server}> {1}No custom Rounds points system defined!"
sys_no_relays = "{#server}> {#error}No relay servers connected"
sys_relaymaster = "{#server}> This server relays master server: {#highlite}{1}{#server} ({#highlite}{2}{#server})"
sys_notonrelay = "{#server}> {#error}Command unavailable on relay server"
sys_uptodate_ok = "{#server}>> {#message}This PyXaseco version {#highlite}{1}{#message} is up to date"
sys_uptodate_new = "{#server}>> {#message}New PyXaseco version {#highlite}{1}{#message} available from {#highlite}{2}"
sys_banip_dialog = "{#welcome}Your IP was banned from this server.$z"
sys_banip_error = "{#welcome}Could not connect:{br}{br}Your IP was banned from this server!"
sys_client_dialog = "{#welcome}Obsolete client version, please $l[http://www.tm-forum.com/viewtopic.php?p=139752#p139752]upgrade$l.$z"
sys_client_error = "{#welcome}Obsolete client version!{br}Please upgrade to the $l[http://www.tm-forum.com/viewtopic.php?p=139752#p139752]latest version$l."
sys_connect_dialog = "{#welcome}Connection problem, please retry.$z"
sys_connect_error = "{#welcome}$sThis is an administrative notice.$z{br}{br}PyXaseco encountered a very rare player connection{br}problem. Please re-join the server to correct it.{br}Apologies for the inconvenience.{br}{br}$sThe server administrators."
sys_idlekick_play = "{#server}>> IdleKick player {#highlite}{1}$z$s{#server} after {#highlite}{2}{#server} challenge{3}!"
sys_idlespec_play = "{#server}>> IdleSpec player {#highlite}{1}$z$s{#server} after {#highlite}{2}{#server} challenge{3}"
sys_idlekick_spec = "{#server}>> IdleKick spectator {#highlite}{1}$z$s{#server} after {#highlite}{2}{#server} challenge{3}!"
sys_song = "{#server}> Track {#highlite}{1} {#server}plays song: {#highlite}{2}"
sys_mod = "{#server}> Track {#highlite}{1} {#server}uses mod: {#highlite}{2} {#server}({#highlite}{3}{#server})"
sys_coppers = "{#server}> Server {#highlite}{1}$z$s {#server}owns {#highlite}{2} {#server}coppers!"
sys_time = "{#server}> {#interact}Current Server Time: {#highlite}$i {1}{#interact} on {#highlite}$i {2}"
sys_tmxrec = "{#server}>> {#record}TMX World Record: {#highlite}{1}{#record} by {#highlite}{2}"
sys_round = "$n{#message}R{#highlite}{1}{#message}> "
sys_no_cpsspec = "{#server}> {#highlite}/cpsspec{#server} is not currently enabled on this server."
sys_no_admin = "{#server}> {#error}You have to be in admin list to do that!"
sys_help_explanation = "{#server}> Press the {#highlite}C{#server} key to see the whole list, and use {#highlite}/helpall{#server} for details"
sys_united_only = "{#server}> {#error}This requires a TM United Forever {1}!"
sys_forever_only = "{#server}> {#error}Command only available on TM Forever!"

[local_messages]
local_record_new = "{#server}>> {#highlite}{1}{#record} secured his/her {#rank}{2}{#record}. Local Record!  {3}: {#highlite}{4}{#record} $n({#rank}{5}{#highlite}{6}{#record})"
local_record_equal = "{#server}>> {#highlite}{1}{#record} equaled his/her {#rank}{2}{#record}. Local Record!  {3}: {#highlite}{4}"
local_record_new_rank = "{#server}>> {#highlite}{1}{#record} gained the {#rank}{2}{#record}. Local Record!  {3}: {#highlite}{4}{#record} $n({#rank}{5}{#highlite}{6}{#record})"
local_record_first = "{#server}>> {#highlite}{1}{#record} claimed the {#rank}{2}{#record}. Local Record!  {3}: {#highlite}{4}"

[dedi_messages]
dedi_welcome = "{#welcome}Welcome to the Dedimania world record system at www.dedimania.com - see {#highlite}/helpdedi"
dedi_timeout = "{#dedimsg}Dedimania system timed out - retrying in {#highlite}{1}{#dedimsg} minutes"
dedi_ranking = "{#server}>> {#dedimsg}Dedimania Record rankings on {#highlite}{1}{#dedimsg} {2} this round:"
dedi_ranking_range = "{#server}>> {#dedimsg}Dedimania Record rankings on {#highlite}{1}{#dedimsg} {2} this round (range {#highlite}{3}{#dedimsg}):"
dedi_ranking_new = "{#server}>> {#dedimsg}Dedimania Record rankings on {#highlite}{1}{#dedimsg} {2} this round ({#highlite}{3}{#dedimsg} new):"
dedi_ranking_nonew = "{#server}>> {#dedimsg}Dedimania Record rankings on {#highlite}{1}{#dedimsg} {2} this round: none new so far"
dedi_ranking_none = "{#server}>> {#dedimsg}Dedimania Record rankings on {#highlite}{1}{#dedimsg} {2} this round: no records!"
dedi_record_new = "{#server}>> {#highlite}{1}{#dedirec} secured his/her {#rank}{2}{#dedirec}. Dedimania Record!  {3}: {#highlite}{4}{#dedirec} $n({#rank}{5}{#highlite}{6}{#dedirec})"
dedi_record_equal = "{#server}>> {#highlite}{1}{#dedirec} equaled his/her {#rank}{2}{#dedirec}. Dedimania Record!  {3}: {#highlite}{4}"
dedi_record_new_rank = "{#server}>> {#highlite}{1}{#dedirec} gained the {#rank}{2}{#dedirec}. Dedimania Record!  {3}: {#highlite}{4}{#dedirec} $n({#rank}{5}{#highlite}{6}{#dedirec})"
dedi_record_first = "{#server}>> {#highlite}{1}{#dedirec} claimed the {#rank}{2}{#dedirec}. Dedimania Record!  {3}: {#highlite}{4}"
dedi_first_record = "{#server}> {#dedirec}The first Dedimania record is: "
dedi_last_record = "{#server}> {#dedirec}The last Dedimania record is: "
dedi_diff_record = "{#server}> {#dedirec}Difference between {1}{#dedirec} and {2}{#dedirec} is: {#highlite}{3}"
dedi_pb = "{#server}> {#dedirec}Dedimania Personal Best: {#highlite}{1}{#dedirec}({#rank}{2}{#dedirec})"
dedi_pb_none = "{#server}> {#error}You don't have a Dedimania record on this track yet..."
dedi_banned_login = "{#server}>> {#highlite}{1} {#server}({#highlite}{2}{#server}) {#error}is banned from Dedimania!"
dedi_banned_finish = "{#server}> {#error}Finish ignored by Dedimania as you are banned!"

[rasp_messages]
rasp_rank = "{#server}> {#record}Your server rank is {#rank}{1}{#record}/{#highlite}{2}{#record} Average: {#highlite}{3}"
rasp_rank_none = "{#server}> {#record}You must have {#highlite}{1}{#record} Local Records on this server before recieving a rank..."
rasp_nextrank = "{#server}> {#record}The next better ranked player is {#highlite}{1}{#record}: {#highlite}{2}"
rasp_nextrank_rp = " $n{#record}[{#highlite}-{1}{#record} RP]"
rasp_toprank = "{#server}> {#record}No better ranked player :-)"
rasp_pb = "{#server}> {#record}Personal Best: {#highlite}{1}{#record}({#rank}{2}{#record}) Average: {#highlite}{3}"
rasp_pb_none = "{#server}> {#error}You don't have a Local Record on this track yet..."
rasp_jukebox = "{#server}>> {#highlite}{1}{#emotic} was added to the jukebox by {#highlite}{2}"
rasp_jukebox_already = "{#server}> {#emotic}You already have a track in the jukebox! Wait till it's been played before adding another."
rasp_jukebox_dupl = "{#server}> {#emotic}This track has already been added to the jukebox, pick another one."
rasp_jukebox_repeat = "{#server}> {#emotic}This track has been played recently. Wait a while before adding it again."
rasp_jukebox_next = "{#server}>> {#emotic}The next track will be {#highlite}{1}{#emotic} as requested by {#highlite}{2}"
rasp_jukebox_nextenv = "{#server}>> {#emotic}The next track will be {#timelite}[{1}] {#highlite}{2}{#emotic} as requested by {#highlite}{3}"
rasp_jukebox_skipleft = "{#server}>> {#emotic}Track {#highlite}{1}{#emotic} skipped because {#highlite}{2}{#emotic} left..."
rasp_jukebox_ignored = "{#server}> {#emotic}Track {#highlite}{1}{#emotic} ignored: {#error}{2}"
rasp_jukebox_drop = "{#server}>> {#emotic}Player {#highlite}{1}{#emotic} dropped his/her track {#highlite}{2}{#emotic} from jukebox!"
rasp_jukebox_nodrop = "{#server}> {#emotic}You don't have a track in the jukebox, use {#highlite}/jukebox Track_ID{#emotic} to add one..."
rasp_jukebox_add = "{#server}>> {#highlite}{1}{#emotic} is requesting {#highlite}{2}{#emotic} from {3}.{br}{#emotic}This will require {#highlite}{4}{#emotic} votes to pass. Type {#highlite}/y{#emotic} to vote yes."
rasp_jukebox_y = "{#server}>> {#highlite}{1}{#emotic} more vote{2} needed to add {#highlite}{3}{#emotic}. Type {#highlite}/y{#emotic} to vote yes."
rasp_jukebox_pass = "{#server}>> {#emotic}Vote Passed! {#highlite}{1}{#emotic} has been added to the jukebox."
rasp_jukebox_end = "{#server}>> {#emotic}Vote to add {#highlite}{1}{#emotic} {2} by {#highlite}{3}{#emotic}!"
rasp_jukebox_cancel = "{#server}>> {#emotic}Current /add vote cancelled!"
rasp_jukebox_notfound = "{#server}> {#emotic}Track_ID not found - Type {#highlite}/list{#emotic} to see all tracks."
rasp_jukebox_empty = "{#server}> {#emotic}No tracks in the jukebox, use {#highlite}/jukebox Track_ID{#emotic} to add one..."
rasp_jukebox_help = "{#server}> {#emotic}You have to include a Track_ID, e.g {#highlite}/jukebox 12{#emotic} - Type {#highlite}/jukebox help{#emotic} for more info."
rasp_jukebox_list = "{#server}> {#emotic}Upcoming tracks in the jukebox: "
rasp_list_help = "{#server}> {#emotic}Use {#highlite}/list{#emotic} first - Type {#highlite}/list help{#emotic} for more info."
rasp_no_jukebox = "{#server}> {#highlite}/jukebox{#emotic} is not currently enabled on this server."
rasp_history = "{#server}> {#emotic}Recently played tracks: "
rasp_add_present = "{#server}> {#highlite}Track already in server list, not added."
rasp_add_presentjb = "{#server}> {#highlite}Track already in server list, adding via jukebox."
rasp_add_dupl = "{#server}> {#emotic}Track is already /add-ed to jukebox."
rasp_no_add = "{#server}> {#highlite}/add{#emotic} is not currently enabled on this server."
rasp_track_too_large = "{#server}> {#error}Track is too large ({#highlite}{1}$i{#error} > 1024 KB) - not added!"
rasp_vote_explain = "{#server}>> {#vote}CallVotes disabled - see {#highlite}/helpvote{#vote} for info on chat-based voting"
rasp_vote_already = "{#server}> {#error}A vote is already in progress. Wait for this to complete."
rasp_vote_limit = "{#server}> {#error}Already ran {#highlite}$i {1}{#error} {2} vote{3} for this track - that's enough!"
rasp_vote_start = "{#server}>> {#highlite}{1}{#vote} is requesting to {#highlite}{2}{#vote}.{br}{#vote}This will require {#highlite}{3}{#vote} votes to pass. Type {#highlite}/y{#vote} to vote yes."
rasp_vote_y = "{#server}>> {#highlite}{1}{#vote} more vote{2} needed to {#highlite}{3}{#vote}. Type {#highlite}/y{#vote} to vote yes."
rasp_vote_pass = "{#server}>> {#vote}Vote Passed! Server to {#highlite}{1}{#vote}."
rasp_vote_end = "{#server}>> {#vote}Vote to {#highlite}{1}{#vote} {2} by {#highlite}{3}{#vote}!"
rasp_vote_cancel = "{#server}>> {#vote}Current vote cancelled!"
rasp_no_more_replay = "{#server}> {#vote}No more than {#highlite}{1}{#vote} replay{2} per track allowed!"
rasp_no_admin_kick = "{#server}>> {#vote}Player {#highlite}{1}{#vote} fruitlessly tried to kick-vote {#logina}admin {#highlite}{2}{#vote}!"
rasp_no_admin_ignore = "{#server}>> {#vote}Player {#highlite}{1}{#vote} fruitlessly tried to ignore-vote {#logina}admin {#highlite}{2}{#vote}!"
rasp_ask_admin = "{#server}> {#error}Chat-based votes disabled - ask the currently available admin to"
rasp_no_spectators = "{#server}> {#error}Spectators not allowed to start votes!"
rasp_no_sb_vote = "{#server}> {#error}Chat-based votes disabled during scoreboard!"
rasp_no_vote = "{#server}> {#error}Chat-based votes disabled - use normal CallVotes."
rasp_karma = "{#server}>> {#karma}Current Track Karma: {#highlite}{1}"
rasp_karma_track = "{#server}>> {#karma}Track {#highlite}{1}{#karma} Karma: {#highlite}{2}"
rasp_karma_details = "{1} $n{#karma}[++: {#highlite}{2}{#karma} ({#highlite}{3}%{#karma}), --: {#highlite}{4}{#karma} ({#highlite}{5}%{#karma})]"
rasp_karma_vote = " $n{#karma}$i{Your vote:  {#highlite}$i{1}{#karma}$i}"
rasp_karma_done = "{#server}> {#highlite}Vote Successful!"
rasp_karma_change = "{#server}> {#highlite}Vote Changed!"
rasp_karma_fail = "{#server}> {#highlite}Vote Failed!"
rasp_karma_voted = "{#server}> {#highlite}You have already voted for this track"
rasp_karma_remind = "{#server}> {#karma}Remember to vote karma ({#highlite}/++{#karma} or {#highlite}/--{#karma}) for this track"
rasp_karma_require = "{#server}> {#error}You need to finish this track at least {#highlite}$i {1}{#error} time{2} before voting!"
rasp_karma_nopublic = "{#server}>> {#error}Public karma votes disabled, use $i{#highlite}/++{#error} or $i{#highlite}/--{#error} instead!"
rasp_nextmap = "{#server}> The next Challenge will be: {#highlite}{1}"
rasp_nextenvmap = "{#server}> The next Challenge will be: {#timelite}[{1}] {#highlite}{2}"
rasp_official = "{#server}> {#highlite}That is not a valid command on ANY server - just wait until the next track to become official."
rasp_bootme = "{#server}>> {#highlite}{1}$z$s{#message} chooses to boot back to the real world."
rasp_bootme_dialog = "{#message}Thanks for playing, please come back soon!"
