phase = 1
controller = "PyXaseco_v1.2"

[loadout]
enabled = [
"core/localdb",
"core/rounds",
"core/track",
"core/chatlog",
"core/checkpoints",
"core/donate",
"core/uptodate",
"bridge/server_admin_bridge",
"bridge/discord",
"bridge/public_stats",
"chat/admin",
"chat/help",
"chat/records",
"chat/records2",
"chat/recrels",
"chat/dedimania",
"chat/players",
"chat/players2",
"chat/wins",
"chat/laston",
"chat/lastwin",
"chat/stats",
"chat/server",
"chat/songmod",
"chat/me",
"service/tmx",
"service/dedimania",
"service/trial_records",
"service/records_rpg",
"service/discord_webhook",
#"service/freezone",
"service/mania_karma",
"feature/rasp",
"feature/rasp_jukebox",
"feature/rasp_chat",
"feature/rasp_nextmap",
"feature/rasp_nextrank",
"feature/rasp_votes",
"feature/jfreu",
"feature/cplive",
"feature/best_cp_times_v2",
#"feature/bestcps",
"feature/bestfinishes",
#"feature/bestruns",
#"feature/bestsecs",
"feature/cpll",
"feature/tmxvideo",
"feature/ztrack",
"ui/style",
"ui/panels",
"ui/records_eyepiece/plugin",
"ui/banner",
"ui/fufi_menu"
#"ui/stalker_actionids",
#"ui/stalker_tools",
#"ui/tgj_allbutton"
]
