[bestsecs]

[bestsecs.config]
compare_own_rec_to_self = "1"
remove_sec_from_db = "1"

[bestsecs.config.position]
xpos = "-59.5"
ypos = "-32"

[bestsecs.config.display_recs]
sec_recs = "1"
own_recs = "1"

[bestsecs.config.window_enabled]
ta = "1"
rounds = "1"
team = "1"
cup = "1"
lap = "1"
stunts = "1"
