[plugin_rasp]
feature_ranks = true
feature_stats = true
always_show_pb = false
nextrank_show_rp = true
prune_records_times = false
reset_cache_start = true
maxrecs = 500
minrank = 3
maxavg = 10
feature_votes = true
vote_in_window = false
allow_spec_startvote = false
allow_spec_voting = false
disable_upon_admin = false
disable_while_sb = false
allow_kickvotes = false
allow_admin_kick = false
allow_ignorevotes = false
allow_admin_ignore = false
ladder_fast_restart = false
auto_vote_starter = false
max_laddervotes = 1
max_replayvotes = 1
max_skipvotes = 1
replays_limit = 0
vote_ratios = [0.5, 0.5, 0.5, 0.5, 0.6, 0.5, 0.5]
r_expire_limit = [1, 3, 3, 3, 3, 3, 3]
r_show_reminder = true
r_points_limits = false
ta_expire_limit = [120, 240, 240, 180, 180, 180, 180]
ta_show_reminder = true
ta_show_interval = 60
ta_time_limits = false
r_ladder_max = 0.5
r_replay_min = 0.5
r_skip_max = 0.8
ta_ladder_max = 0.5
ta_replay_min = 0.5
ta_skip_max = 0.8
global_explain = 1

[plugin_rasp_chat]
pm_buf_len = 30
line_len = 70

[plugin_rasp_jukebox]
tmx_download_dir = "TMX"
