[plugin_cplive_v3]
max_display_rows = 24
pos_x = -64.4
pos_y = 19
widget_update_interval = 100
min_widget_update_interval = 50
strict_mode = false
leader_mode = false
allow_nick_style_toggle = true
plain_nicks = false
show_spectators = true
use_spectator_icon = true
show_spectator_targets = true
toggle_key = 0
